### ISSUE TITLE
Stm32F105 usb driver for android

### ISSUE THREAD

**Issue by ali313** [once2go/Stm32-Android-Accessory#1]
Hi
I programmed your code to my stm32F105 module but my android phone won't detect module.
Is there any android app for detecting and comunication with module.
also used this guide of google documents for creating android app to detect the module but I did not succeed
https://developer.android.com/guide/topics/connectivity/usb/accessory

Do I need a usb driver for using your code in my android app? If yes, where can I find it?

thanks in advance

**Comment by once2go** [comment]
Do you have some developer board or just MCU?

**Comment by elias-hatami** [comment]
I have the same problem
Help me please


-------------------------------------------------------------------
[Photo link developer board:](http://s4.trainbit.com/v/7199898484/j1.jpg)
http://s4.trainbit.com/v/7199898484/j1.jpg

[Schematic link developer board:](http://trainbit.com/files/9299898484/Schematic.pdf)
http://trainbit.com/files/9299898484/Schematic.pdf

**Comment by once2go** [comment]
Do you have any log printed to uart? 
Did you flash the project from example or did you build everything from scratch as it described in readme? 
There are no driver requirement and no indication at all from android side until you will request access to accessory. Check this video https://youtu.be/RyH69WQR5VE 
In any case I need log from your board otherwise it's hard to say where is your issue.

**Comment by elias-hatami** [comment]
We downloaded your code from github. And we entered in Stm32CubIDE software and flashed on the microcontroller without any changes.

No, we did not establish any software or hardware connection with uart

**Can you upload the sample source code(Export Stm32cubeIDE softweare) microcontroller(Stm32F105) and Android  used in the YouTube link(youtu.be/RyH69WQR5VE)?
Or send it to us?**

**Comment by once2go** [comment]
> but my android phone won't detect module!!?

 - what Android phone do you use? 
 

> Can you upload the sample source code(Export Stm32cubeIDE softweare) microcontroller(Stm32F105) and Android used in the YouTube link(youtu.be/RyH69WQR5VE)?
> Or send it to us? 

This code is a part of commercial project and I can't share it. But you can build your app. using this [documentation](https://developer.android.com/guide/topics/connectivity/usb/accessory) or you can use [AOSP adk app reference](https://android.googlesource.com/device/google/accessory/adk2012/+/refs/heads/master/src/com/google/android/apps/adk2) 

> ---No, we did not establish any software or hardware connection with uart
It's hard to understand what is wrong without log.
